title: "Travel Zynelion"
description: "Catatan travel, itinerary, dan tips perjalanan yang ringan dibaca."
theme: null
markdown: kramdown
permalink: /:year/:month/:day/:title.html

url: "https://travel.zynelion.com"
baseurl: ""

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
